### ISSUE TITLE
v2 bugs for mines

### ISSUE THREAD

**Issue by blitzwolfz** [JonathanTheZero/Utopia#23]
- [x] Fix mine dig time bug
- [x] Fix mine 0 minereturn variable bug
- [x] Add some commenting to mine file

**Comment by blitzwolfz** [comment]
![Capture](https://user-images.githubusercontent.com/16308843/79820466-4966f180-835a-11ea-8042-a30ef87fc3f5.PNG)

**Comment by JonathanTheZero** [comment]
Mines have been fixed, it was some small mathematical error by you, everything works as intended again
