### ISSUE TITLE
Update bot to Discordjs v12

### ISSUE THREAD

**Issue by blitzwolfz** [JonathanTheZero/Utopia#34]
Since discord decided to change their API on a whim, v11 will now soon be deprecated in favour of v12. Should make a new branch and start working on that after current government features are completed.

**Comment by JonathanTheZero** [comment]
Yes I will do, maybe even prioritize this over the expanded government mechanics as a lot of things don't work due to that.
However, I found a way to at least fix all server-intern messages, only messaging external users is problematic

**Comment by blitzwolfz** [comment]
Well I think v12 is more important external server messaging, so should put our focus on this rather than a message system

**Comment by JonathanTheZero** [comment]
Hold on, this whole message system was your idea

**Comment by blitzwolfz** [comment]
Not as important as upgrading to v12

**Comment by JonathanTheZero** [comment]
Done
